<a href="https://colab.research.google.com/github/garimaakashyap/numpy/blob/main/g_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [31]:
# garima learning numpy library of python

NumPy is a general-purpose array-processing package.

It provides a high-performance mutlidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python.

In [32]:
# first we have to install the nump


In [33]:
# we have to import the numpy
import numpy as np

In [34]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [35]:
type(arr)

numpy.ndarray

In [36]:
arr

array([1, 2, 3, 4, 5])

In [37]:
print(my_lst)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [38]:
# telling the length of the array
arr.shape

(5,)

In [39]:
# creating 2d array
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3=[11,12,13,14,15]
ar = np.array([l1,l2,l3])
print(ar)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [40]:
# checking the size
print(ar.shape)

# 3 is number of row and 5 is number of column

(3, 5)


In [41]:
# changing the shape of the array means its row and column size, but it should be always equal to the rows*columns of the original array
print(ar.reshape(5,3))
print(ar.shape)
print(ar)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
(3, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [42]:
ar.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [43]:
ar.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [44]:
print(ar.reshape(15,1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [45]:
a = ar.reshape(5,3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [46]:
# indexing
a1 = np.array([10,20,30,40])
print(a1)

[10 20 30 40]


In [47]:
print(a1[3])

40


In [48]:
# indexing in 2d array

a2 = np.array([
    [1,2,3,4,5],
    [56,67,78,87,102],
    [3,4,5,6,7]
])
print(a2)

[[  1   2   3   4   5]
 [ 56  67  78  87 102]
 [  3   4   5   6   7]]


In [49]:
for i in a2:
  print(a2)

[[  1   2   3   4   5]
 [ 56  67  78  87 102]
 [  3   4   5   6   7]]
[[  1   2   3   4   5]
 [ 56  67  78  87 102]
 [  3   4   5   6   7]]
[[  1   2   3   4   5]
 [ 56  67  78  87 102]
 [  3   4   5   6   7]]


In [50]:
for i in a2:
  for j in i:
    print(j, end=" ")
  print()

1 2 3 4 5 
56 67 78 87 102 
3 4 5 6 7 


for printing particular element or range of elements

In [51]:
# bydefault it will take the whole row and column

a2[:,:]

array([[  1,   2,   3,   4,   5],
       [ 56,  67,  78,  87, 102],
       [  3,   4,   5,   6,   7]])

In [52]:
# it will exclude 1 and 4 remember

print(a2[0:1,2:4])

[[3 4]]


In [53]:
print(a2[1:2,2:3])

[[78]]


In [54]:
# copy function and broadcasting

arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr3)

arr3[4:] = 108
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4 108 108 108 108 108 108]


In [55]:
a3 = np.array([1,2,3,4,5,6,7,8,9])
a4 = np.array([11,22,33,4,4,44,55])

print(a3)
print(a4)
print()

a5= a3
a6 = a4.copy()

print(a5)
print(a6)
print()

a5[3:] = 500
a6[4:] = 98

print("a3 ",a3)
print("a4 ",a4)
print("a5 ",a5)
print("a6 ",a6)




[1 2 3 4 5 6 7 8 9]
[11 22 33  4  4 44 55]

[1 2 3 4 5 6 7 8 9]
[11 22 33  4  4 44 55]

a3  [  1   2   3 500 500 500 500 500 500]
a4  [11 22 33  4  4 44 55]
a5  [  1   2   3 500 500 500 500 500 500]
a6  [11 22 33  4 98 98 98]


some in-built functions

In [60]:
p1 = np.zeros((2,3))       # array of zeros
p2 = np.ones((3,2))        # array of ones
p3 = np.arange(0,10,2)     # [0 2 4 6 8]
p4 = np.linspace(0,1,5)    # [0. 0.25 0.5 0.75 1.]
p5 = np.eye(3)             # identity matrix

print(p1)
print()
print(p2)
print()
print(p3)
print()
print(p4)
print()
print(p5)

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Array Operations

NumPy allows to do mathematical operations directly on arrays, just like with numbers — no loops needed.

In [61]:


a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Element-wise Multiplication
print(a / b)   # Division
print(a ** 2)  # Power


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


Scalar Operations

In [63]:
p = np.array([1, 2, 3])

print(p + 5)   # [6 7 8]
print(p * 10)  # [10 20 30]


[6 7 8]
[10 20 30]


Matrix Operations

In [65]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(np.dot(x, y))   # Matrix multiplication
print()
print(x @ y)          # Same as np.dot

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


Comparison Operations

In [66]:
c = np.array([10, 20, 30, 40])

print(c > 20)     # [False False  True  True]
print(c == 10)    # [ True False False False]


[False False  True  True]
[ True False False False]


Mathematical Functions

In [67]:
arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))   # Average
print(np.max(arr))    # Maximum
print(np.min(arr))    # Minimum
print(np.sum(arr))    # Sum
print(np.sqrt(arr))   # Square root
print(np.exp(arr))    # Exponential
print(np.log(arr))    # Natural log


3.0
5
1
15
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


indexing

1D array

In [69]:


arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # First element → 10
print(arr[-1])  # Last element → 50

arr[2] = 99
print(arr)  # [10 20 99 40 50]



10
50
[10 20 99 40 50]


Slicing (1D Arrays)

In [70]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])   # Elements from index 1 to 3 → [20 30 40]
print(arr[:3])    # First 3 elements → [10 20 30]
print(arr[3:])    # From index 3 to end → [40 50 60]
print(arr[::2])   # Every 2nd element → [10 30 50]


[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]


Indexing (2D Arrays)

In [71]:
b = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print(b[0, 1])   # Row 0, Column 1 → 20
print(b[2, 2])   # Row 2, Column 2 → 90

b[1, 1] = 999
print(b)



20
90
[[ 10  20  30]
 [ 40 999  60]
 [ 70  80  90]]


Slicing (2D Arrays)

In [72]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(b[0:2, 1:3])   # Rows 0–1, Cols 1–2 → [[2 3] [5 6]]
print(b[:, 1])       # All rows, column 1 → [2 5 8]
print(b[1, :])       # Row 1, all columns → [4 5 6]


[[2 3]
 [5 6]]
[2 5 8]
[4 5 6]


Boolean Indexing

In [73]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])   # [30 40 50]
print(arr[arr % 20 == 0])  # [20 40]


[30 40 50]
[20 40]


linspace n arrange


arange(start, stop, step)

linspace(start, stop, num)

In [74]:
print(np.arange(0, 10, 2))  # [0 2 4 6 8]
print(np.linspace(0, 1, 5)) # [0.   0.25 0.5  0.75 1.  ]


[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
